# Generated by Django 6.0.7 on 2026-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('lat', models.FloatField(verbose_name='纬度（GCJ-02）')),
                ('lng', models.FloatField(verbose_name='经度（GCJ-02）')),
                ('trigger_radius', models.IntegerField(default=50, verbose_name='触发半径（米）')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='景点图片 URL')),
                ('audio_url', models.CharField(blank=True, default='', max_length=500, verbose_name='音频 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'db_table': 'spots',
                'ordering': ['id'],
            },
        ),
    ]
