# Generated by Django 6.0.7 on 2026-07-14 08:42

import apps.spots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='image_url',
        ),
        migrations.AddField(
            model_name='spot',
            name='audio',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.spots.models.audio_upload_path, verbose_name='音频文件'),
        ),
        migrations.AddField(
            model_name='spot',
            name='image',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.spots.models.image_upload_path, verbose_name='景点图片'),
        ),
    ]
