# Generated by Django 6.0.7 on 2026-07-15 09:25

import apps.spots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_remove_spot_audio_url_remove_spot_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.spots.models.image_upload_path, verbose_name='景点图片'),
        ),
    ]
