# Generated by Django 6.0.7 on 2026-07-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_alter_spot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='category',
            field=models.CharField(choices=[('college', '学院'), ('nature', '自然景观'), ('architecture', '特色建筑'), ('teaching', '教学区'), ('service', '生活服务'), ('humanity', '人文景观')], default='architecture', max_length=20, verbose_name='分类'),
        ),
    ]
