# Generated by Django 6.0.7 on 2026-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_add_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='trigger',
            field=models.JSONField(blank=True, null=True, verbose_name='触发区域几何（JSON）'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='category',
            field=models.CharField(default='architecture', max_length=20, verbose_name='分类'),
        ),
    ]
