# Generated by Django 6.0.7 on 2026-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'db_table': 'global_config',
            },
        ),
    ]
